#!/usr/bin/env python

import argparse
import email
import poplib
import socket
import shutil
from tempfile import NamedTemporaryFile


parser = argparse.ArgumentParser(description='POP3 Mail Attachment Saver.')
parser.add_argument('server', type=str, help='A POP3 mail server')
parser.add_argument('user', type=str, help='A POP3 user name')
parser.add_argument('password', type=str, help='A POP3 password')
parser.add_argument('filename', type=str, help='A filename to save an attachment to')
args = parser.parse_args()

try:
    mbox = poplib.POP3(args.server)
    mbox.user(args.user)
    mbox.pass_(args.password)
except poplib.error_proto, message:
    print 'POP3 Protocol Error:', message
    exit(1)
except socket.error:
    print 'Unable to connect to the server "%s"' % args.server
    exit(1)

numMessages = len(mbox.list()[1])
if not numMessages:
    print 'No messages found.'
    exit()

for i in range(numMessages):
    message = mbox.retr(i+1)[1]
    #message = email.message_from_bytes(b'\n'.join(message))
    message = email.message_from_string('\n'.join(message))

    for part in message.walk():
        if part.get_content_maintype() == 'multipart':
            continue

        if part.get('Content-Disposition') is None:
            continue

        f = NamedTemporaryFile(delete=False)
        f.write(part.get_payload(decode=1))
        f.close()

    shutil.move(f.name, args.filename)
    mbox.dele(i+1)
    print 'An attachment was succesfully saved to file "%s"' % args.filename

mbox.quit()
